# Generated by Django 2.0.2 on 2018-03-12 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigoCientifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='titulo')),
                ('autores', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculo', models.TextField()),
                ('artigos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='feira.ArtigoCientifico')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('eventoPrincipal', models.TextField()),
                ('dataEHoraDeInicio', models.DateTimeField(auto_now_add=True)),
                ('palavrasChave', models.TextField()),
                ('logotipo', models.TextField()),
                ('cidade', models.TextField()),
                ('uf', models.CharField(max_length=2, verbose_name='uf')),
                ('endereco', models.TextField()),
                ('cep', models.CharField(max_length=9, verbose_name='cep')),
            ],
        ),
        migrations.CreateModel(
            name='EventoCientifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issn', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=50, verbose_name='cnpj')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=50, verbose_name='cnpj')),
                ('razaoSocial', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='relizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='feira.Pessoa'),
        ),
        migrations.AddField(
            model_name='artigocientifico',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventocientifico', to='feira.EventoCientifico'),
        ),
    ]
