# Generated by Django 2.0.2 on 2018-03-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feira', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigocientifico',
            name='autores',
            field=models.CharField(max_length=150, verbose_name='autores'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='curriculo',
            field=models.CharField(max_length=150, verbose_name='curriculo'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='endereco',
            field=models.CharField(max_length=70, verbose_name='endereco'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='eventoPrincipal',
            field=models.CharField(max_length=200, verbose_name='eventoPrincipal'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='logotipo',
            field=models.CharField(max_length=100, verbose_name='logotipo'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='palavrasChave',
            field=models.CharField(max_length=300, verbose_name='palavrasChave'),
        ),
        migrations.AlterField(
            model_name='eventocientifico',
            name='issn',
            field=models.CharField(max_length=100, verbose_name='issn'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.CharField(max_length=120, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='razaoSocial',
            field=models.CharField(max_length=550, verbose_name='razaoSocial'),
        ),
    ]
